src/main/java/amdn/anywhere/controller/MessageController.java
src/main/java/amdn/anywhere/domain/MessageCommon.java
src/main/java/amdn/anywhere/mapper/MessageMapper.java
src/main/java/amdn/anywhere/service/MessageService.java
src/main/resources/mapper/MessageMapper.xml
src/main/resources/templates/fragments/leftsidebar.html
src/main/resources/templates/message/commonMessage.html
src/main/resources/templates/message/messageCheck.html
src/main/resources/templates/message/messageList.html

공통메시지/받은메시지목록/메세지체크 -[1차]

---

src/main/java/amdn/anywhere/controller/BookController.java
src/main/java/amdn/anywhere/controller/MainController.java
src/main/java/amdn/anywhere/domain/Menu.java
src/main/java/amdn/anywhere/domain/Statement.java
src/main/java/amdn/anywhere/mapper/BookMapper.java
src/main/java/amdn/anywhere/service/BookService.java
src/main/resources/mapper/BookMapper.xml
src/main/resources/mapper/MainMapper.xml
src/main/resources/templates/book/addBookMember.html
src/main/resources/templates/book/addBookOrder.html
src/main/resources/templates/fragments/leftsidebar.html
src/main/resources/templates/main.html

주문정보입력 화면 수정

---

src/main/resources/templates/fragments/leftsidebar.html

[team_project] 재무관리 / 이름추가

---

src/main/java/amdn/anywhere/controller/MainController.java
src/main/java/amdn/anywhere/domain/Menu.java
src/main/java/amdn/anywhere/mapper/MainMapper.java
src/main/java/amdn/anywhere/service/MainService.java
src/main/resources/mapper/MainMapper.xml
src/main/resources/templates/book/addBookOrder.html
src/main/resources/templates/main.html

main화면 ajax 구현완료

---

src/main/java/amdn/anywhere/controller/BoardController.java
src/main/java/amdn/anywhere/domain/BoardCate.java
src/main/java/amdn/anywhere/domain/Member.java
src/main/java/amdn/anywhere/mapper/BoardMapper.java
src/main/java/amdn/anywhere/service/BoardService.java
src/main/resources/mapper/BoardMapper.xml
src/main/resources/templates/board/boardList.html
src/main/resources/templates/board/boardWrite.html

게시판 ajax구현진행

---

src/main/java/amdn/anywhere/controller/MessageController.java
src/main/java/amdn/anywhere/mapper/MessageMapper.java
src/main/java/amdn/anywhere/service/MessageService.java
src/main/resources/mapper/MessageMapper.xml
src/main/resources/templates/message/addMessage.html
src/main/resources/templates/message/commonMessage.html
src/main/resources/templates/message/messageCheck.html
src/main/resources/templates/message/messageCheckList.html
src/main/resources/templates/message/messageList.html

[메세지목록]-Ajax 완료

---

src/main/java/amdn/anywhere/controller/BoardController.java
src/main/java/amdn/anywhere/domain/Board.java
src/main/java/amdn/anywhere/mapper/BoardMapper.java
src/main/java/amdn/anywhere/service/BoardService.java
src/main/resources/mapper/BoardMapper.xml
src/main/resources/templates/board/boardList.html
src/main/resources/templates/board/boardModify.html
src/main/resources/templates/board/boardView.html
src/main/resources/templates/board/boardWrite.html

[게시판 ajax 구현 완료 , 게시판 등록 구현 완료, 게시판 정보 구현 진행 중]

[게시판 ajax 구현 완료 , 게시판 등록 구현 완료, 게시판 정보 구현 진행 중]

---

src/main/java/amdn/anywhere/controller/BoardController.java
src/main/java/amdn/anywhere/controller/BookController.java
src/main/java/amdn/anywhere/controller/MainController.java
src/main/java/amdn/anywhere/interceptor/CommonInterceptor.java
src/main/java/amdn/anywhere/mapper/BookMapper.java
src/main/java/amdn/anywhere/service/BookService.java
src/main/resources/mapper/BookMapper.xml
src/main/resources/templates/book/addBookMember.html
src/main/resources/templates/book/addBookOrder.html
src/main/resources/templates/main.html

[ 메인화면 ajax / 주문화면 수량 자바스크립트 구현]

[ 메인화면 ajax / 주문화면 수량 자바스크립트 구현]

---

src/main/java/amdn/anywhere/interceptor/CommonInterceptor.java
src/main/resources/mapper/MessageMapper.xml
src/main/resources/templates/message/messageList.html

[메세지목록]-Ajax 완료1

---

src/main/java/amdn/anywhere/controller/BoardController.java
src/main/resources/static/css/style.css
src/main/resources/templates/board/boardList.html
src/main/resources/templates/book/addBookMember.html
src/main/resources/templates/book/addBookOrder.html
src/main/resources/templates/fragments/leftsidebar.html
src/main/resources/templates/main.html

[ajax css수정 / 주문화면 수량체크 구현 ]

---

src/main/resources/templates/fragments/leftsidebar.html

[메뉴 담당기별 이름 수정 ]

---

src/main/java/amdn/anywhere/controller/MessageController.java
src/main/java/amdn/anywhere/domain/MessageCheck.java
src/main/java/amdn/anywhere/mapper/MessageMapper.java
src/main/java/amdn/anywhere/service/MessageService.java
src/main/resources/mapper/MessageMapper.xml
src/main/resources/templates/fragments/leftsidebar.html
src/main/resources/templates/message/messageCheck.html
src/main/resources/templates/message/messageCheckList.html
src/main/resources/templates/message/messageList.html

[메세지 알림 설정]-update 기능 완료

---

src/main/java/amdn/anywhere/controller/BoardController.java
src/main/java/amdn/anywhere/domain/Board.java
src/main/java/amdn/anywhere/mapper/BoardMapper.java
src/main/java/amdn/anywhere/service/BoardService.java
src/main/resources/mapper/BoardMapper.xml
src/main/resources/templates/board/boardList.html
src/main/resources/templates/board/boardModify.html
src/main/resources/templates/board/boardView.html
src/main/resources/templates/board/boardWrite.html

[게시판 crud구현 진행]

---

src/main/java/amdn/anywhere/controller/BookController.java
src/main/java/amdn/anywhere/controller/MainController.java
src/main/java/amdn/anywhere/controller/PosOrderController.java
src/main/java/amdn/anywhere/domain/Store.java
src/main/java/amdn/anywhere/domain/Waiting.java
src/main/java/amdn/anywhere/mapper/MainMapper.java
src/main/java/amdn/anywhere/service/MainService.java
src/main/resources/mapper/MainMapper.xml
src/main/resources/templates/book/addBookMember.html
src/main/resources/templates/book/addBookOrder.html
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/main.html
src/main/resources/templates/pos/posOrder.html

[ 메인화면/주문화면 구현 ]

---

src/main/java/amdn/anywhere/controller/BoardController.java
src/main/java/amdn/anywhere/mapper/BoardMapper.java
src/main/java/amdn/anywhere/service/BoardService.java
src/main/resources/mapper/BoardMapper.xml
src/main/resources/templates/board/boardList.html
src/main/resources/templates/board/boardModify.html
src/main/resources/templates/board/boardMyView.html

[게시판 조회수, 권한에 따른 수정 삭제 기능 구현]

---

src/main/java/amdn/anywhere/controller/BookController.java
src/main/java/amdn/anywhere/domain/Order.java
src/main/java/amdn/anywhere/mapper/BookMapper.java
src/main/java/amdn/anywhere/service/BookService.java
src/main/resources/mapper/BookMapper.xml
src/main/resources/templates/book/addBookMember.html
src/main/resources/templates/book/addBookOrder.html
src/main/resources/templates/main.html

[ 예약대기 조회 / 최종주문 후 insert작업 진행중 ]

[ 예약대기 조회 // 최종주문 후 insert작업 진행중 ]

---

src/main/java/amdn/anywhere/controller/BookController.java
src/main/java/amdn/anywhere/controller/MainController.java
src/main/java/amdn/anywhere/domain/Order.java
src/main/resources/mapper/BookMapper.xml
src/main/resources/templates/book/addBookMember.html
src/main/resources/templates/book/addBookOrder.html
src/main/resources/templates/main.html

[ 예약코드/주문코드 자동증가 수정 ]

---

src/main/java/amdn/anywhere/controller/BoardController.java
src/main/resources/templates/board/boardList.html
src/main/resources/templates/board/boardWrite.html

[ajax 권한 별 보이는 창 다르게 하기]

---

src/main/java/amdn/anywhere/controller/MessageController.java
src/main/java/amdn/anywhere/mapper/MessageMapper.java
src/main/java/amdn/anywhere/service/MessageService.java
src/main/resources/templates/message/messageList.html

[메세지 리스트 선택삭제 화면만]

---

src/main/java/amdn/anywhere/controller/BookController.java
src/main/resources/mapper/BookMapper.xml
src/main/resources/templates/book/addBookMember.html
src/main/resources/templates/book/addBookOrder.html

[체크박스이벤트/주문정보입력구현진행중]

---

src/main/java/amdn/anywhere/controller/BoardController.java
src/main/java/amdn/anywhere/domain/Member.java
src/main/java/amdn/anywhere/mapper/BoardMapper.java
src/main/resources/mapper/BoardMapper.xml
src/main/resources/templates/board/boardList.html
src/main/resources/templates/board/boardModify.html
src/main/resources/templates/board/boardMyView.html
src/main/resources/templates/board/boardView.html
src/main/resources/templates/board/boardWrite.html

[게시판 css화면 변경]

---

src/main/java/amdn/anywhere/controller/BadWordsController.java
src/main/java/amdn/anywhere/controller/BoardController.java
src/main/java/amdn/anywhere/domain/BadWords.java
src/main/java/amdn/anywhere/mapper/BadWordsMapper.java
src/main/java/amdn/anywhere/service/BadWordsService.java
src/main/resources/mapper/BadWordsMapper.xml
src/main/resources/mapper/BoardMapper.xml
src/main/resources/templates/badwords/commonBadWords.html
src/main/resources/templates/board/boardList.html
src/main/resources/templates/board/boardModify.html
src/main/resources/templates/board/boardMyView.html
src/main/resources/templates/board/boardView.html
src/main/resources/templates/board/boardWrite.html
src/main/resources/templates/fragments/leftsidebar.html
src/main/resources/templates/main.html

[금지어 목록 리스트 , 메뉴 수정]

---

src/main/java/amdn/anywhere/controller/StoreController.java
src/main/java/amdn/anywhere/domain/Menu.java
src/main/java/amdn/anywhere/domain/MenuCate.java
src/main/java/amdn/anywhere/mapper/MenuMapper.java
src/main/java/amdn/anywhere/service/MenuService.java
src/main/java/amdn/anywhere/service/StoreService.java
src/main/resources/mapper/BookMapper.xml
src/main/resources/mapper/MenuMapper.xml
src/main/resources/templates/book/addBookMember.html
src/main/resources/templates/book/addBookOrder.html
src/main/resources/templates/fragments/leftsidebar.html
src/main/resources/templates/main.html
src/main/resources/templates/store/myStoremanage/addMyMenu.html
src/main/resources/templates/store/myStoremanage/myMenuManage.html
src/main/resources/templates/store/myStoremanage/myStoreInfo.html
src/main/resources/templates/store/myStoremanage/myStoreModify.html

[매장 메뉴등록 구현중]

---

src/main/java/amdn/anywhere/controller/BookController.java
src/main/java/amdn/anywhere/controller/StoreController.java
src/main/java/amdn/anywhere/domain/Store.java
src/main/java/amdn/anywhere/interceptor/CommonInterceptor.java
src/main/java/amdn/anywhere/mapper/MenuMapper.java
src/main/java/amdn/anywhere/mapper/StoreMapper.java
src/main/java/amdn/anywhere/service/BookService.java
src/main/java/amdn/anywhere/service/StoreService.java
src/main/resources/mapper/MenuMapper.xml
src/main/resources/mapper/StoreMapper.xml
src/main/resources/templates/book/addBookMember.html
src/main/resources/templates/book/addBookOrder.html
src/main/resources/templates/pos/posOrder.html
src/main/resources/templates/store/myStoremanage/addMyMenu.html
src/main/resources/templates/store/myStoremanage/myMenuManage.html
src/main/resources/templates/store/myStoremanage/myStoreInfo.html
src/main/resources/templates/store/myStoremanage/myStoreModify.html
src/main/resources/templates/store/storeManage.html
src/main/resources/templates/store/storeModify.html

[메뉴관리 구현진행중]

---

src/main/java/amdn/anywhere/controller/BadWordsController.java
src/main/java/amdn/anywhere/controller/BoardController.java
src/main/java/amdn/anywhere/domain/BoardReply.java
src/main/java/amdn/anywhere/mapper/BoardMapper.java
src/main/java/amdn/anywhere/service/BoardService.java
src/main/resources/mapper/BoardMapper.xml
src/main/resources/templates/board/boardMyView.html
src/main/resources/templates/board/boardView.html

[게시판 댓글 css구현 및 기능구현 진행 중]

---

src/main/java/amdn/anywhere/controller/StoreController.java
src/main/java/amdn/anywhere/mapper/StoreMapper.java
src/main/java/amdn/anywhere/service/StoreService.java
src/main/resources/mapper/StoreMapper.xml
src/main/resources/templates/store/myStoreManage/modifyMainCate.html
src/main/resources/templates/store/myStoreManage/modifyMyMenu.html
src/main/resources/templates/store/myStoreManage/myMenuManage.html

[메뉴관리 등록,수정,삭제 구현완료]

---

src/main/java/amdn/anywhere/controller/BoardController.java
src/main/java/amdn/anywhere/domain/BoardReply.java
src/main/java/amdn/anywhere/mapper/BoardMapper.java
src/main/java/amdn/anywhere/service/BoardService.java
src/main/resources/mapper/BoardMapper.xml
src/main/resources/templates/board/boardList.html
src/main/resources/templates/board/boardMyView.html
src/main/resources/templates/board/boardView.html

[게시판 댓글 조회,등록 구현 완료/삭제처리진행 중]

---

src/main/java/amdn/anywhere/controller/BoardController.java
src/main/java/amdn/anywhere/controller/ReportController.java
src/main/java/amdn/anywhere/mapper/ReportMapper.java
src/main/java/amdn/anywhere/service/ReportService.java
src/main/resources/mapper/ReportMapper.xml
src/main/resources/templates/board/boardList.html
src/main/resources/templates/board/boardView.html
src/main/resources/templates/report/reportBoardList.html

[게시판 신고 구현 완료]

---

src/main/java/amdn/anywhere/controller/EnterController.java
src/main/java/amdn/anywhere/controller/StoreController.java
src/main/java/amdn/anywhere/domain/Store.java
src/main/java/amdn/anywhere/domain/StoreCancel.java
src/main/java/amdn/anywhere/mapper/StoreMapper.java
src/main/java/amdn/anywhere/service/StoreService.java
src/main/resources/mapper/StoreMapper.xml
src/main/resources/templates/enter/addStore.html
src/main/resources/templates/enter/cancelMyStore.html
src/main/resources/templates/enter/cancelStore.html
src/main/resources/templates/enter/cancelStoreManage.html
src/main/resources/templates/fragments/leftsidebar.html

[매장관리 구현진행중]

---

src/main/java/amdn/anywhere/controller/BoardController.java
src/main/java/amdn/anywhere/controller/ReportController.java
src/main/java/amdn/anywhere/domain/Penalty.java
src/main/java/amdn/anywhere/domain/PenaltyStandard.java
src/main/java/amdn/anywhere/domain/Report.java
src/main/java/amdn/anywhere/mapper/BoardMapper.java
src/main/java/amdn/anywhere/mapper/ReportMapper.java
src/main/java/amdn/anywhere/service/BoardService.java
src/main/java/amdn/anywhere/service/ReportService.java
src/main/resources/mapper/BoardMapper.xml
src/main/resources/mapper/ReportMapper.xml
src/main/resources/templates/board/boardBizReport.html
src/main/resources/templates/board/boardReport.html
src/main/resources/templates/fragments/leftsidebar.html
src/main/resources/templates/report/penaltyInsert.html
src/main/resources/templates/report/penaltyList.html

[게시판 벌점 부과,삭제,조회 구현완료]

---

src/main/java/amdn/anywhere/controller/BookController.java
src/main/java/amdn/anywhere/controller/EnterController.java
src/main/java/amdn/anywhere/controller/MainController.java
src/main/java/amdn/anywhere/controller/PosController.java
src/main/java/amdn/anywhere/controller/StoreController.java
src/main/java/amdn/anywhere/mapper/BookMapper.java
src/main/java/amdn/anywhere/mapper/MainMapper.java
src/main/java/amdn/anywhere/mapper/PosMapper.java
src/main/java/amdn/anywhere/service/BookService.java
src/main/java/amdn/anywhere/service/MainService.java
src/main/java/amdn/anywhere/service/PosService.java
src/main/resources/mapper/BookMapper.xml
src/main/resources/mapper/MainMapper.xml
src/main/resources/mapper/PosMaaper.xml
src/main/resources/static/icons/themify-icons/themify-icons.css
src/main/resources/templates/book/addBookMember.html
src/main/resources/templates/book/bookMyOrderList.html
src/main/resources/templates/book/bookOrderList.html
src/main/resources/templates/enter/addStore.html
src/main/resources/templates/fragments/leftsidebar.html
src/main/resources/templates/main.html
src/main/resources/templates/pos/posMain.html
src/main/resources/templates/pos/posOrder.html
src/main/resources/templates/store/myStoreManage/myTableManage.html

th:text="${o.statement.StateName}"

[메인 주소,카테고리검색 구현/pos화면구현중]
